const data = {
  products: [
    {
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/nt1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: '4.5',
      numReviews: '10',
      description: 'high quality shirt',
    },
    {
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/np1.jpg',
      price: 45,
      countInStock: 15,
      brand: 'Nike',
      rating: '4.5',
      numReviews: '14',
      description: 'high quality pant',
    },
    {
      name: 'Adidas Slim shirt',
      slug: 'adidas-slim-shirt',
      category: 'Shirts',
      image: '/images/at1.jpg',
      price: 130,
      countInStock: 15,
      brand: 'Adidas',
      rating: '4.4',
      numReviews: '18',
      description: 'high quality shirt',
    },
    {
      name: 'Adidas Slim pant',
      slug: 'adidas-slim-pant',
      category: 'Pants',
      image: '/images/ap1.jpg',
      price: 80,
      countInStock: 20,
      brand: 'Adidas',
      rating: '4.3',
      numReviews: '20',
      description: 'high quality pant',
    },
  ],
};
export default data;
